name: Talk Request
description: Request a topic
title: "[Request]: "
labels: ["request"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this talk request form!
  - type: textarea
    id: request
    attributes:
      label: The Request
      description: What are you requesting?
    validations:
      required: true
